In [2]:
#Boolean Indexing
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a[a>4]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
a[a==0]=-1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [5]:
a== -1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
a=np.arange(12).reshape(3,4)
a[np.logical_and(a>3,a<=9)]=0.0
a

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [7]:
a>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [8]:
#Avoiding Loops
M=45
N=56
xmin=ymin=0.0
xmax=ymax=1.0
x=np.linspace(xmin,xmax,M,endpoint=False)
y=np.linspace(xmin,xmax,M,endpoint=False)
print(x.shape)
print(y.shape)
y

(45,)
(45,)


array([0.        , 0.02222222, 0.04444444, 0.06666667, 0.08888889,
       0.11111111, 0.13333333, 0.15555556, 0.17777778, 0.2       ,
       0.22222222, 0.24444444, 0.26666667, 0.28888889, 0.31111111,
       0.33333333, 0.35555556, 0.37777778, 0.4       , 0.42222222,
       0.44444444, 0.46666667, 0.48888889, 0.51111111, 0.53333333,
       0.55555556, 0.57777778, 0.6       , 0.62222222, 0.64444444,
       0.66666667, 0.68888889, 0.71111111, 0.73333333, 0.75555556,
       0.77777778, 0.8       , 0.82222222, 0.84444444, 0.86666667,
       0.88888889, 0.91111111, 0.93333333, 0.95555556, 0.97777778])

In [22]:
import time
import numpy as np
M=32
N=64
x=np.linspace(0.0,1.0,M,endpoint=False)
y=np.linspace(0.0,1.0,N,endpoint=False)

In [24]:
t0=time.time()
g=np.zeros((M,N))
print(g)
for i in range(M):
    for j in range(N):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
t1=time.time()
print("time.elapsed:{} s".format(t1-t0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
time.elapsed:0.003292560577392578 s


In [25]:
x2d,y2d=np.meshgrid(x,y,indexing="ij")
print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])
      
      

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [31]:
t0=time.time()
g2=np.sin(2.0*np.pi*x2d*y2d)
t1=time.time()
print("time.elapsed:{} s".format(t1-t0))


time.elapsed:0.00018072128295898438 s


In [32]:
# Numpy Standard Data Types
#Array Concatenation and Splitting
#Concatenation Of Arrays
x=np.array([1,2,3,4])
y=np.array([4,3,2,1])
np.concatenate([y,x])

array([4, 3, 2, 1, 1, 2, 3, 4])

In [33]:
z=[5,6,9]
print(np.concatenate([x,y,z]))

[1 2 3 4 4 3 2 1 5 6 9]


In [34]:
grid=np.array([[20,30,40],
              [50,60,70]])

In [35]:
#Concatenate along the first axis
np.concatenate([grid,grid])

array([[20, 30, 40],
       [50, 60, 70],
       [20, 30, 40],
       [50, 60, 70]])

In [36]:
#Concatenate along the second axis(zero-indexed)
np.concatenate([grid,grid],axis=1)

array([[20, 30, 40, 20, 30, 40],
       [50, 60, 70, 50, 60, 70]])

In [37]:
#Splitting of arrays
x=[1,2,4,5,6,5,6,5,4,2,1,2,9,4,]
x1,x2,x3,x4=np.split(x,[3,6,9])
print(x1,x2,x3,x4)

[1 2 4] [5 6 5] [6 5 4] [2 1 2 9 4]


In [38]:
grid=np.arange(25).reshape((5,5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [40]:
#Aggregates
x=np.arange(1,5)
print(x)
np.add.reduce(x)

[1 2 3 4]


np.int64(10)

In [41]:
np.multiply.reduce(x)

np.int64(24)

In [42]:
np.add.accumulate(x)

array([ 1,  3,  6, 10])

In [43]:
np.multiply.accumulate(x)

array([ 1,  2,  6, 24])